Repository gravitystorm/openstreetmap-carto, pull requests merged in 2018-05, with the labels that each got.

#2763 Adding area rendering for amenity=bus_station
  landcover.mss
  project.mml
Labels: input needed

#2640 Render “surface” tag on roads with a pattern
  project.mml
  roads.mss
  scripts/colors_bd.c
  scripts/generate_unpaved_patterns.py
  symbols/unpaved/unpaved.md
  symbols/unpaved/unpaved.svg
  symbols/unpaved/unpaved_aeroway-fill.svg
  symbols/unpaved/unpaved_living-street-fill.svg
  symbols/unpaved/unpaved_motorway-fill.svg
  symbols/unpaved/unpaved_motorway-low-zoom.svg
  symbols/unpaved/unpaved_pedestrian-fill.svg
  symbols/unpaved/unpaved_platform-fill.svg
  symbols/unpaved/unpaved_primary-fill.svg
  symbols/unpaved/unpaved_primary-low-zoom.svg
  symbols/unpaved/unpaved_raceway-fill.svg
  symbols/unpaved/unpaved_residential-fill.svg
  symbols/unpaved/unpaved_road-fill.svg
  symbols/unpaved/unpaved_secondary-fill.svg
  symbols/unpaved/unpaved_trunk-fill.svg
  symbols/unpaved/unpaved_trunk-low-zoom.svg
Labels: roads

#2946 Adding natural and semi natural areas to use cases
  USECASES.md
Labels: input needed

#2874 Dropping subpixel accuracy for areas
  indexes.sql
  indexes.yml
  project.mml
Labels: input needed, performance
