Repository gravitystorm/openstreetmap-carto, pull requests merged in 2019-10, with the labels that each got.

#3911 Documentation of inner line rendering
  admin.mss
Labels: documentation

#3942 Apply bbox to part of "addresses" query
  project.mml
Labels: performance

#3922 Remove natural=marsh from amenity-points
  amenity-points.mss
Labels: code

#3915 Precedence of junctions over POIs
  project.mml
Labels: text

#3912 Don't use classes anymore
  .travis.yml
  amenity-points.mss
  landcover.mss
  placenames.mss
  project.mml
  roads.mss
  shapefiles.mss
  water.mss
Labels: code

#3910 Update Docker documentation
  DOCKER.md
Labels: documentation

#3919 Fix rendering of water body labels
  amenity-points.mss
  water.mss
Labels: bug

#3930 Create darker river-color for river & canal areas and ditch, drain, stream, canal & river lines
  project.mml
  style.mss
  symbols/intermittent_river.png
  water.mss
Labels: water

#3923 Move parking back to amenity-points layers, change way_pixels limit and fix initial zoom level
  amenity-points.mss
  project.mml
Labels: bug

#3955 Revert PR #3930 which added river-color
  project.mml
  style.mss
  water.mss
Labels: water
