Repository gravitystorm/openstreetmap-carto, pull requests merged in 2020-01, with the labels that each got.

#3973 Import man_made=pipeline, man_made=cutline and power=cable as linestrings
  openstreetmap-carto.lua
Labels: lua

#3932 Use ST_PointOnSurface for roads-area-text-name
  project.mml
  roads.mss
Labels: code

#3844 Remove polygon fill rendering for barrier=hedge
  landcover.mss
  project.mml
Labels: barrier, enhancement

#3902 Use ST_PointOnSurface for bridge names
  project.mml
  roads.mss
Labels: code

#4010 Remove rendering of barrier=embankment
  landcover.mss
  project.mml
Labels: barrier, remove rendering

#4003 Import aerialway=station as a polygon feature
  openstreetmap-carto.lua
Labels: lua

#3964 Only use text-dy for wind generators, not for other power=generator features
  amenity-points.mss
Labels: bug, text

#3950 Remove way_pixels selection from bridge layer
  project.mml
Labels: code

#3947 Remove name from SQL select when unused
  project.mml
Labels: code

#3921 Change text-poly-low-zoom to use ST_PointOnSurface
  amenity-points.mss
  project.mml
Labels: code

#3933 Use ST_PointOnSurface for junctions
  project.mml
Labels: code

#3965 Remove operator text label rendering for amenity=vending_machine
  amenity-points.mss
Labels: remove rendering, text
