Repository gravitystorm/openstreetmap-carto, pull requests merged in 2020-04, with the labels that each got.

#4059 Add rendering for landuse=salt_pond
  project.mml
  style/amenity-points.mss
  style/landcover.mss
  symbols/salt_pond.png
  symbols/salt_pond.svg
Labels: new features, pattern, water

#4082 Render addr:flats
  project.mml
  style/addressing.mss
Labels: addressing, new features

#4100 Rework admin boundaries and show admin_level=5/6/7 sooner, level=10 later
  project.mml
  style/admin.mss
  style/placenames.mss
Labels: admin

#4096 Remove rendering of residential, unclassified, cycleway, footway, path highway areas
  project.mml
  style/roads.mss
Labels: remove rendering

#4102 Render man_made=goods_conveyor
  project.mml
  style/aerialways.mss
Labels: new features

#4094 Change wetland pattern initial zoom to z10 again
  project.mml
  style/landcover.mss
Labels: pattern

#4085 Render place=square in amenity-points layer with placenames style from z17
  project.mml
  style/amenity-points.mss
  style/placenames.mss
Labels: placenames, text

#4087 Remove the rendering of waterways with tunnel=flooded
  project.mml
Labels: water

#4072 Render bare_rock pattern from z13, same as shingle and scree
  style/landcover.mss
Labels: pattern

#4126 Restore admin-text rendering for admin_level 3 to 5
  style/admin.mss
Labels: bug
