Repository gravitystorm/openstreetmap-carto, pull requests merged in 2021-01, with the labels that each got.

#4281 update to growing issue count
  README.md
Labels: documentation

#4280 Create a partial index for waterways
  indexes.sql
  indexes.yml
Labels: performance

#4218 Render mini-roudabout just like a turning circle
  project.mml
  style/amenity-points.mss
  style/roads.mss
  symbols/highway/mini_roundabout.svg
Labels: roads
