Repository gravitystorm/openstreetmap-carto, pull requests merged in 2022-07, with the labels that each got.

#4587 Change symbol for Christian denominations that don't use cross
  CHANGELOG.md
  style/amenity-points.mss
Labels: amenity-points

#4589 Fail CI if YAML files aren't valid
  .github/workflows/ci.yml
Labels: general

#4600 Use barrier icon for gate fill
  symbols/barrier/gate.svg
Labels: amenity-points

#4591 Remove healthcare dead code
  style/amenity-points.mss
Labels: amenity-points

#4609 User friendly improvements to get-external-data.py
  DOCKER.md
  docker-compose.yml
  scripts/docker-startup.sh
  scripts/get-external-data.py
Labels: code

#4313 Public transport shelter should not be labeled with elevation
  project.mml
Labels: bug, amenity-points

#4628 Correct the disable JIT command
  INSTALL.md
Labels: bug, code
